name: Build and deploy new container
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Fetch Zenodo Versions"]
    types:
      - completed
jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository files onto the runner
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Verify the files are copied
      - name: List files
        run: ls -la

      # Step 3: Build Docker Image From Newest Repo
      - name: Build Docker Image
        run: docker buildx build --platform=linux/amd64 -t mmccoy1234/software-citation-station:1.0 .

      # Step 4: Make sure Docker Image Built Successfully
      - name: List Docker Images
        run: docker image ls
